### ISSUE TITLE
Fix the logo on pages other than the landing page

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#115]
Should look like:
![Screen Shot 2018-01-25 at 9.10.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53d30e7b82b317f7d9ad0fbb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f66b7191a371f1132b4f5f565ecc3c4a4356bcbbd671f3e57862804e0ee4d66b0e27976f17afbf8518b701ba21d94ed4e4ed8a4dd2f42f67b6d5db1063474f4dcbed5727a19141c95df74de84e5cac173463ef7f2431.png)
Instead, on any page besides the landing page if you load that page directly it looks like:
![Screen Shot 2018-01-25 at 9.08.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53d30e7b82b317f7d9ad0fbb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f66b7191a371f112234f5c565ecc3c4a4356bcbbd671f3e57862804e0ee4d66b0e27976f17afbf8518b701ba21d94ed4e4ed8a4dd2f42f67b6d5db1063474f4dcbed5727a19041c95df74de84e5cac133562e4762431.png)

Probably just need to set `img` `src` to have a leading slash e.g. `<img src="/something" />` instead of `<img src="something" />`

**Comment by KeynesYouDigIt** [comment]
I can take this if someone wants to add me as a collaborator! finally got my dev env up after giving up on docker :(

**Comment by KeynesYouDigIt** [comment]
@wdoug we cant reproduce this, might have been covered ? - is there a specific page you see it broken on? /volunteers works for me (logo shows up fine)

**Comment by KeynesYouDigIt** [comment]
its something path related. when I go to /me/edit I see http://localhost:3000/me/images/cfd-circle-white.png as the request for the image. whats particularly strange is that returns a 304, not a 404
