### ISSUE TITLE
Design interface for specifying different amounts of skills and levels of interest

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#149]
For reference, here is what we did for a members form in the past.
![Screen Shot 2018-02-26 at 7.42.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53d30e7b82b317f7d9ad0fbb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f56b7191a37ff116294f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ee4d66b0e27976f17afbf8518b701ba21d94ed4e4ed8a4dd2f42f67b6d5db1063474f4dcbed5727a19041c95df742e7445ca7153162e2732431.png)

I think we could design a better interface, but maybe have the same levels of skill/interest to start

**Comment by jbrennan414** [comment]
See Figma for additional design options
