### ISSUE TITLE
Design workflow for projects to specify requests for help

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#150]

**Comment by jbrennan414** [comment]
![cfd1.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e5502942a3720011528cd1/125516c66e82c728ace21e0d46eb929e72c0cfeb9ffbb049a15ee4d67304722a7e52a2287187b57be8152c595f5f4ffe40090d15fcf89b37b4f46d2ede0356b49b381d66cc2f10abb2831abd03bd228a4784b0b48f44d2a5.jpeg)

**Comment by jbrennan414** [comment]
![cfd2.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e5502942a3720011528cd1/125516c66e82c728ace21e0d46eb929e71c0cfeb9ffbb049a15ee4d67304722a7e52a2287187b57be8152c595f5f4ffe40090d15fcf89b37b4f46d2ede0356b49b381d66cc2f10abb2831abd03bd228a4786b7b58b4cd2a5.jpeg)

**Comment by eemshi** [comment]
`help wanted` in Github Issues
