### ISSUE TITLE
Figure out how we want to keep track of the status of projects

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#165]
I think there are at least two possibilities here. We  could pull from the [this project waffle board](https://waffle.io/codefordenver/projects), or we could have a separate field in the project in graphcool.

**Comment by eemshi** [comment]
Exploring the use of Github repo tags

**Comment by fredmon3** [comment]
Would the civic.json Status be sufficient?
"Ideation" - brainstorming phase.
"Alpha" - initial prototyping phase and internal testing.
"Beta" - a product is being tested in public.
"Production" - finished Product, with development and maintenance ongoing.
"Archival" - finished Product, but no longer actively maintained.
