### ISSUE TITLE
Add UI for setting and viewing project champions

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#195]
Projects can have champions. Let's update the UI to show them. Designs can be seen [here](https://www.figma.com/file/dHAyvZXkSvRW4nC5Q7JhoD3g/code-for-denver-members-project-1)

Depends on #162

**Comment by cvanem** [comment]
From wdoug: I have a setup for form components (that notably could use some refactoring to clean up a bit) that allows components to be used for both editing and viewing purposes. I believe we should be able to use the EditableList component similar to how it is used by EditableSkills for but for users to be selected for project champions 18:0
