### ISSUE TITLE
Tracking: Architecture Considerations

### ISSUE THREAD

**Issue by dchao19** [codefordenver/members#203]
1. Continue with #179 and pull REST data and GraphQL data in the client
2. Client side GraphQL management (GraphQL Anywhere)
3. Only client-side integrations and eliminate the backend
4. Add a proxy layer for schema stitching on the server.

GET
- List of repos
- Issues for each repo
- metadata about contributions -- for later

**Comment by wdoug** [comment]
We decided to continue as previously and just add an Apollo Rest link for pulling some additional metadata from Rest APIs like Github
