### ISSUE TITLE
Architecture: Only client-side integrations and eliminate the backend

### ISSUE THREAD

**Issue by dchao19** [codefordenver/members#206]
Child of #203

**Comment by lcrostarosa** [comment]
curl https://api.github.com/users/codefordenver/repos

-- now I have all repos

for (repo in repos) {
  curl https://api.github.com/repos/codefordenver/${repo.name}/contributors
  curl https://api.github.com/repos/codefordenver/members/events
  
}

**Comment by lcrostarosa** [comment]
Per @wdoug -- CFA api does similar functionality and may even provide a wrapper.
