### ISSUE TITLE
[spike] Use cfapi to pull data for repos tagged "active-project" as the source of truth for projects

### ISSUE THREAD

**Issue by eemshi** [codefordenver/members#214]
Get:
- [ ] Repo name, description, url
- [ ] Issues labeled "help wanted" or "good first issue"

**Comment by wdoug** [comment]
I couldn't find how to filter issues for a specific project, only for a specific organization. If this is true and we still want that functionality, we'd probably want to either query the github api directly or make a pull request to the [code for america api repo](https://github.com/codeforamerica/cfapi).

**Comment by wdoug** [comment]
I'm going to keep the graph.cool data as the source of truth for the list of projects for now but just pull info from github as additional information for now.
