### ISSUE TITLE
[spike] how to make project page sidebar responsive

### ISSUE THREAD

**Issue by eemshi** [codefordenver/members#218]

**Comment by jberns** [comment]
Material UI has a responsive drawer we can look at

https://material-ui.com/demos/drawers/#responsive-drawer

**Comment by eemshi** [comment]
@jberns Nice! I'm going to take a stab at fixing this mockup so we can start building

**Comment by eemshi** [comment]
Here's an updated version that's more simplified:
![Screen Shot 2018-05-22 at 5.08.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/569dcda79e118a0e000cfbd0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f16b7191a37df112234f5d595ecc3c4a4356bcbbd671f3e57862804e0ee4d66b0e27976f17afbf8518b701ba21d94ed4e4ed8a4dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce14e55a1103060e1722431.png)

Not so sure about the "Background" tab - couldn't think of what to put there (might not need anything at all)

**Comment by jberns** [comment]
I got the example code mostly working.  Need to decide where to put the menu bar when the sidebar is closed.  Before it would appear on a second "AppBar" component but we don't need two on the same page.  

Other items to fix:
* Need to fix CSS as the sidebar position does not move down when the current "AppBar" take up two lines
* Need to fix the routes/project details page to show the Drawer sidebar component
* Need to add an active button when a specific project is selected.



![sidebaropen.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad54e7fbc78070012265678/125516c66e82c728ace21e0d46fb9d9e268082bb80f9ba4de611b2843b492d762a10e17132d0ba7fe94378000d594dab465f5744fcf8db2af7e46d708b4e17ff933c0120996048e6edc00db513bb29814e80b4bb8a4fc1e0392ce18a8b5d73.PNG)

![sidebarclosed.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad54e7fbc78070012265678/125516c66e82c728ace21e0d46fb9d9e268082bb8ce5b050a159b2d86b56357c2301a03f32dfa17de6152d000c0e1caa425f5843f4f9892af4b76d22db5c0affcd7f1d2598694ef1e1c84afd13b0328a488fb7b9884bc0eb3c2de382894e3a0c48.PNG)
