### ISSUE TITLE
[spike] how to 1:1 someone on flowdock from members page list

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/members#219]
https://members.codefordenver.org/volunteers

**Comment by ZadenRB** [comment]
https://www.flowdock.com/api Will probably be needed. Docs relevant to this issue are probably:
https://www.flowdock.com/api/private-conversations
and
https://www.flowdock.com/api/private-messages

**Comment by dviramontes** [comment]
@ZadenRB great thanks, i was not able to authenticate with the API last time I tried. I would be down to pair on this if you have time. LMK!

**Comment by ZadenRB** [comment]
@dviramontes sounds good, I'll probably be there thursday. If you are, we can pair then.

**Comment by dviramontes** [comment]
need to find the user's flowdock ID and then we can generate a link out to flodock:
`https://www.flowdock.com/app/private/346875`

**Comment by wdoug** [comment]
@Wenhan129 what was the status of this work?

**Comment by wdoug** [comment]
We're moving away from flowdock so this is no longer relevant. We might want to investigate this for Discord in the future, but that can be a new issue
