### ISSUE TITLE
Add remaining CFD project IDs to production member site

### ISSUE THREAD

**Issue by jberns** [codefordenver/members#228]
http://api.codeforamerica.org/api/organizations/Code-for-Denver

**Comment by wdoug** [comment]
At this point, we've realized that the Code for America API [isn't adequate for this](https://www.flowdock.com/app/cfa-brigades/members-project/threads/D1MlcAgrRWgTMYTtqI_yeFUQPK4). I'm going to keep the card for a moment though as I'd like to change the site to get data from Github directly and that will require this same update on the existing projects
