### ISSUE TITLE
Refactor graphql testing

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#321]
Use format outlined in this excellent blog post:
https://medium.freecodecamp.org/a-new-approach-to-mocking-graphql-data-1ef49de3d491

An example of doing this can be found here: https://github.com/wdoug/typescript-graphql-and-hooks/commit/f31a14c93bce125cd627b6526c5a4b6540230c9f

**Comment by wdoug** [comment]
I started investigating this, and I'm not sure how to get the executable schema working ([example](https://github.com/wdoug/typescript-graphql-and-hooks/commit/f31a14c93bce125cd627b6526c5a4b6540230c9f#diff-ba4da25d06c6db917c8717899803d56dR109)) since we don't have (or at least I'm not sure how to get) a graphql SDL description of the whole schema

**Comment by MikeLuDev** [comment]
@wdoug I believe this was resolved a recent PR, closing.
