### ISSUE TITLE
Add member since ...

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/members#34]
As a member I would like to see how long I've been contributing to CFD. I would I also like a way to edit my contribution beginning time to reflect actual time.

**Comment by wdoug** [comment]
Investigate pulling this data from meetup (joining meetup or first meetup attended)

**Comment by jbrennan414** [comment]
Made progress on this tonight, but I'm hoping to submit a PR next week. Unfortunately, this won't pull anything from meetup, perhaps we can add that later?

**Comment by wdoug** [comment]
@jpb55116 what is the status of this work? Any chance we could get PR opened? If not, would you mind linking your work-in-progress branch?
