### ISSUE TITLE
Wireframes for site features/interaction

### ISSUE THREAD

**Issue by eemshi** [codefordenver/members#67]
See backlog for feature ideas

**Comment by wdoug** [comment]
Some ideas:

- Onboarding
  - admin inviting to flowdock
  - self-guided learning resources for new members 
- Matching people with needs
  - requesting help
  - seeing what help is needed
- General learning resources
- Admin resources
- Links to different documents

**Comment by jbrennan414** [comment]
![codeforDenver_wireframe1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e5502942a3720011528cd1/125516c66e82c728ace21e0d46eb9b9e26848cbbabecb155a14fcf83205422753b05ae2e21c7af6aaf50740b0a0c0abe4b4a5a4dfbffd878f7e43a738d5b0ce5d16d5e26c76c43fdb8830da313f871d51bdaebe5c01982fa3737e68c854e3b1f03198ffd5f31a39d4dcf4abb.jpg)

**Comment by jbrennan414** [comment]
![cfd-members-whiteboard-wireframe-ideas](https://user-images.githubusercontent.com/5432102/35132092-cc2b3eee-fc86-11e7-8b95-134b281b9538.jpg)

**Comment by jbrennan414** [comment]
Team, I talked to Trinh on Thursday, he'll be doing mock-ups of the designs we've posted here! We can expect some initial designs on Thursday, to be discussed Monday 1/29
