### ISSUE TITLE
Update Auth0 documentation for setup

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#71]

**Comment by wdoug** [comment]
@pwrobitaille what was the status of the updates for this documentation? I see [this branch](https://github.com/codefordenver/members/compare/71-update-Auth0-documentation#diff-04c6e90faac2675aa89e2176d2eec7d8). Is that ready for a pull request?

**Comment by pwrobitaille** [comment]
Hey Will yup that's ready for a pull request
