### ISSUE TITLE
make a <HelpUsImplementThisFeature/> component

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/members#80]
As a developer
> I would like a React component that shows a tooltip of some sort over its child elements that requests help on implementing a feature so that I can easily specify that certain content in the app hasn't been made into a functional feature yet

Additionally this can link to a waffle card associated with the feature needed to be impletemed.

**Comment by sungbae** [comment]
I'm going to use [react-tooltip](https://www.npmjs.com/package/react-tooltip).
