### ISSUE TITLE
feat: display members who joined in the last week

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/members#96]
As a Code for Denver admin, I would like the `EmailList` component to only display emails of members who joined in the last week so I can easily invite them to flowdock.

**Comment by wdoug** [comment]
You can open a graphql playground for our api by running `npm run gc -- playground` from the root of the repo. Clicking on the `schema` button on the right will allow you to explore the generated graphql api.

**Comment by sungbae** [comment]
Just to note, the first commit '#96 add date-fns email list' was to an old branch (000d8cf9c4be7bbce0a5ee4d19a7b8c65a777d5f). I deleted it since I didn't want to deal with a merge conflict in the package-lock.json. Since the change was minor, I went ahead and pulled from master to branch again.
